[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "1.12.0"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = { version = "1.0.87", features = ["preserve_order"] }
sha256 = "1.1.1"
toml = "0.5.9"
